### ISSUE TITLE
SchNetPack/PyTorch Dependency Conflicts

### ISSUE THREAD

**Issue by shaychaudhuri** [atomistic-machine-learning/schnetpack-gschnet#2] opened 2023-02-17 11:11 UTC
Hi, 

I'm experiencing some dependency conflicts and the installation instructions for the repository might need updating. `schnetpack` 2.0.0 requires `pytorch-lightning>=1.8.1` but `pytorch_lightning.loggers.base.LightningLoggerBase` has been [deprecated since v1.7.0](https://pytorch-lightning.readthedocs.io/en/stable/generated/CHANGELOG.html#id47). This results in the following `ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers'`. I've followed the provided installation instructions so the error should be reproducible. Any advice would be very appreciated!

Many thanks, Shay

**Comment by NiklasGebauer** [comment] 2023-02-20 10:32
Hi Shay,

thanks for pointing that out! The error occurs in `schnetpack` due to changes in the API of `pytorch-lightning`.
You have several options to circumvent this problem:

1. Install `pytorch-lightning==1.8.1` manually before you install `schnetpack-gschnet` (since `LightningLoggerBase` was only removed in later versions).
```
git clone https://github.com/atomistic-machine-learning/schnetpack-gschnet.git
conda create -n gschnet numpy
conda activate gschnet
pip install pytorch-lightning==1.8.1
pip install ./schnetpack-gschnet
```
2. Alternatively, install `schnetpack` from source before you install `schnetpack-gschnet` (since the problem is already fixed in the most recent version of `schnetpack`).
```
git clone https://github.com/atomistic-machine-learning/schnetpack-gschnet.git
git clone https://github.com/atomistic-machine-learning/schnetpack.git
conda create -n gschnet numpy
conda activate gschnet
pip install ./schnetpack
pip install ./schnetpack-gschnet
```

Also, we will update the pip release of `schnetpack` as soon as possible. I will update this issue accordingly.

**Comment by shaychaudhuri** [comment] 2023-02-20 15:13
Perfect, yup that seems to have resolved the issue. Thanks Niklas!

**Comment by NiklasGebauer** [comment] 2023-03-22 16:22
Finally closing this issue as SchNetPack has been updated to version 2.0.1 lately and the pip-wheel should not cause conflicts anymore.

**Closed as completed** 2023-03-22 16:22 UTC
